// <auto-generated />
namespace CapstoneProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedregistrationstatusanddayplan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedregistrationstatusanddayplan));
        
        string IMigrationMetadata.Id
        {
            get { return "201707241227444_added registration status and day plan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
